#!/usr/bin/env php

<?php 
var_dump($argv);
var_dump(getopt("p:"));

if ($argv[1] == 'run') {
    if (!isset($argv[2])) {
        exit("app file is missing...");
    }
    
    $appFile = $argv[2];
    
    $http = new swoole_http_server("0.0.0.0", 1314);
    
    $http->on("start", function($server) {
    
        echo "Swoole http server is started at http://0:0:0:0:1314\n";
    
    });
    
    $http->on("workerStart", function($server) use ($appFile) {
    
        $server->app = $app = require_once __DIR__ . "/bootstrap.php";
        
        require_once getcwd() . "/{$appFile}";
        
    });
    
    $http->on("request", function($swooleRequest, $swooleResponse) use ($http) {
        
        if ($swooleRequest->server) {
            foreach($swooleRequest->server as $key => $value) {
                $_SERVER[strtoupper($key)] = $value;
            }
        }
        $_GET = $swooleRequest->get ?? [];
        $_POST = $swooleRequest->post ?? [];
        $_COOKIE = $swooleRequest->cookie ?? [];
        $_FILES = $swooleRequest->files ?? [];
    
        $response = $http->app->handle(Illuminate\Http\Request::capture()); 
    
        $swooleResponse->status($response->getStatusCode());
        $swooleResponse->end($response->getContent());
    
    });
    
    $http->start();
    
}
